apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ''
  labels:
    component: kube-scheduler
    tier: control-plane
  name: k8s-scheduler
  namespace: kube-system
spec:
  hostNetwork: true
  priorityClassName: system-node-critical
  containers:
    - name: k8s-scheduler
      image: {{.DockerRegistry}}/giantswarm/kube-scheduler:v{{ .K8sVersion }}
      command:
      - kube-scheduler
      - --config=/etc/kubernetes/config/scheduler.yaml
      {{if eq .Provider "azure" -}}
      - --feature-gates=CSIMigration=true,CSIMigrationAzureDisk=true
      {{ end -}}
      - --v=2
      - --authorization-always-allow-paths=/healthz,/readyz,/livez,/metrics
      - --authentication-kubeconfig=/etc/kubernetes/kubeconfig/scheduler.yaml
      - --authorization-kubeconfig=/etc/kubernetes/kubeconfig/scheduler.yaml
      resources:
        requests:
          cpu: 200m
          memory: 200Mi
      livenessProbe:
        httpGet:
          host: 127.0.0.1
          path: /healthz
          port: 10259
          scheme: HTTPS
        initialDelaySeconds: 15
        timeoutSeconds: 15
      volumeMounts:
      - mountPath: /etc/kubernetes/ssl/
        name: ssl-certs-kubernetes
        readOnly: true
      - mountPath: /etc/kubernetes/config/
        name: k8s-config
        readOnly: true
      - mountPath: /etc/kubernetes/kubeconfig/
        name: k8s-kubeconfig
        readOnly: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/ssl
    name: ssl-certs-kubernetes
  - hostPath:
      path: /etc/kubernetes/config
    name: k8s-config
  - hostPath:
      path: /etc/kubernetes/kubeconfig
    name: k8s-kubeconfig
