apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-cloud-controller-manager-app-user-values
  namespace: giantswarm
data:
  values: |
    image:
      registry: {{.DockerRegistry}}
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
    app.kubernetes.io/name: aws-cloud-controller-manager-app
  name: aws-cloud-controller-manager-app
  namespace: giantswarm
spec:
  catalog: giantswarm
  config:
    configMap:
      name: ""
      namespace: ""
    secret:
      name: ""
      namespace: ""
  install: {}
  kubeConfig:
    context:
      name: ""
    inCluster: true
    secret:
      name: ""
      namespace: ""
  name: aws-cloud-controller-manager-app
  namespace: kube-system
  namespaceConfig: {}
  userConfig:
    configMap:
      name: "aws-cloud-controller-manager-app-user-values"
      namespace: "giantswarm"
    secret:
      name: ""
      namespace: ""
  version: 1.24.1-gs8
