apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-cloud-controller-manager-user-values
  namespace: giantswarm
data:
  values: |
    cluster:
      calico:
        CIDR: {{ .PodCIDR }}
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
    app.kubernetes.io/name: aws-cloud-controller-manager-app
  name: aws-cloud-controller-manager-app
  namespace: giantswarm
spec:
  catalog: giantswarm-test
  config:
    configMap:
      name: ""
      namespace: ""
    secret:
      name: ""
      namespace: ""
  install: {}
  kubeConfig:
    context:
      name: ""
    inCluster: true
    secret:
      name: ""
      namespace: ""
  name: aws-cloud-controller-manager-app
  namespace: kube-system
  namespaceConfig: {}
  userConfig:
    configMap:
      name: "aws-cloud-controller-manager-user-values"
      namespace: "giantswarm"
    secret:
      name: ""
      namespace: ""
  version: 1.23.2-gs2-ef61cbecacee3f5dcabec298ff3c948ccd401ae2
