apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
    app.kubernetes.io/name: aws-cloud-controller-manager-app
  name: aws-cloud-controller-manager-app
  namespace: giantswarm
spec:
  catalog: control-plane-test-catalog
  config:
    configMap:
      name: ""
      namespace: ""
    secret:
      name: ""
      namespace: ""
  install: {}
  kubeConfig:
    context:
      name: ""
    inCluster: true
    secret:
      name: ""
      namespace: ""
  name: aws-cloud-controller-manager-app
  namespace: kube-system
  namespaceConfig: {}
  userConfig:
    configMap:
      name: ""
      namespace: ""
    secret:
      name: ""
      namespace: ""
  version: 0.0.0-0a6e9c93d3b21f79a7edf97e24d32ec5f0fe1a78
