apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-node-termination-handler-app-values
  namespace: giantswarm
data:
  configmap-values.yaml: |
    queueURL: "{{.ClusterName}}-node-termination"

---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
    app.kubernetes.io/name: aws-node-termination-handler-app
  name: aws-node-termination-handler-app
  namespace: giantswarm
spec:
  catalog: control-plane-catalog
  config:
    configMap:
      name: "aws-node-termination-handler-app-values"
      namespace: "giantswarm"
    secret:
      name: ""
      namespace: ""
  install: {}
  kubeConfig:
    context:
      name: ""
    inCluster: true
    secret:
      name: ""
      namespace: ""
  name: aws-node-termination-handler-app
  namespace: kube-system
  namespaceConfig: {}
  userConfig:
    configMap:
      name: ""
      namespace: ""
    secret:
      name: ""
      namespace: ""
  version: 0.1.0
