apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-ebs-csi-driver-app-user-values
  namespace: giantswarm
data:
  values: |
    controller:
      replicas: 2
      hostNetwork: false
      nodeSelector:
        kubernetes.io/os: linux
    node:
      hostNetwork: false
      nodeSelector:
        kubernetes.io/os: linux
    global:
      image:
        registry: {{.DockerRegistry}}
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
    app.kubernetes.io/name: aws-ebs-csi-driver-app
  name: aws-ebs-csi-driver-app
  namespace: giantswarm
spec:
  catalog: control-plane-catalog
  config:
    configMap:
      name: ""
      namespace: ""
    secret:
      name: ""
      namespace: ""
  install: {}
  kubeConfig:
    context:
      name: ""
    inCluster: true
    secret:
      name: ""
      namespace: ""
  name: aws-ebs-csi-driver-app
  namespace: kube-system
  namespaceConfig: {}
  userConfig:
    configMap:
      name: "aws-ebs-csi-driver-app-user-values"
      namespace: "giantswarm"
    secret:
      name: ""
      namespace: ""
  version: 2.16.1
