apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-user-values
  namespace: giantswarm
data:
  values: |
    hubble:
      relay:
        enabled: true
    defaultPolicies:
      enabled: true
    egressMasqueradeInterfaces: eth0
    eni:
      enabled: false
    kubeProxyReplacement: strict
    k8sServiceHost: "{{ .APIInternalDomainName }}"
    k8sServicePort: "443"
    ipam:
      mode: cluster-pool
      operator:
        clusterPoolIPv4PodCIDR: "{{ .PodCIDR }}"
        clusterPoolIPv4MaskSize: {{ .NodePodCIDRSize }}
    tunnel: vxlan
    nodeinit:
      enabled: true
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
    app.kubernetes.io/name: cilium
  name: cilium
  namespace: giantswarm
spec:
  catalog: default
  config:
    configMap:
      name: ""
      namespace: ""
    secret:
      name: ""
      namespace: ""
  install: {}
  kubeConfig:
    context:
      name: ""
    inCluster: true
    secret:
      name: ""
      namespace: ""
  name: cilium
  namespace: kube-system
  namespaceConfig: {}
  userConfig:
    configMap:
      name: "cilium-user-values"
      namespace: "giantswarm"
    secret:
      name: ""
      namespace: ""
  version: 0.2.0
