apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  name: azure-scheduled-events
  namespace: giantswarm
spec:
  catalog: default
  config:
    configMap:
      name: "" 
      namespace: ""
    secret:
      name: ""
      namespace: ""
  install: {}
  kubeConfig:
    context:
      name: ""
    inCluster: true
    secret:
      name: ""
      namespace: ""
  name: azure-scheduled-events-app
  namespace: kube-system
  namespaceConfig: {}
  userConfig:
    configMap:
      name: ""
      namespace: ""
    secret:
      name: ""
      namespace: ""
  version: 0.6.0

