apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/name: calico-crd-installer
  name: calico-crd-installer-v3.21.3
  namespace: kube-system
spec:
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        app.kubernetes.io/name: calico-crd-installer
    spec:
      containers:
        - name: crd-installer
          image: {{ .DockerRegistry }}/giantswarm/calico-crd-installer:v3.21.3
      hostNetwork: true
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      restartPolicy: Never
      serviceAccountName: calico-init
  backoffLimit: 4
