apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom-values
  namespace: giantswarm
data:
  values: |
    cluster:
      kubernetes:
        clusterDomain: {{ .ClusterDomain }}
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
    app.kubernetes.io/name: coredns
    giantswarm.io/service-type: managed
  name: coredns
  namespace: giantswarm
spec:
  catalog: default
  config:
    configMap:
      name: ""
      namespace: ""
    secret:
      name: ""
      namespace: ""
  install: {}
  kubeConfig:
    context:
      name: ""
    inCluster: true
    secret:
      name: ""
      namespace: ""
  name: coredns-app
  namespace: kube-system
  namespaceConfig: {}
  userConfig:
    configMap:
      name: coredns-custom-values
      namespace: giantswarm
    secret:
      name: ""
      namespace: ""
  version: 1.8.0
