kind: ConfigMap
apiVersion: v1
metadata:
  name: ingress-nginx
  namespace: kube-system
  labels:
    k8s-addon: ingress-nginx.addons.k8s.io
data:
  enable-vts-status: "true"
  enable-ssl-chain-completion: "true"
  {{ if eq .Provider "aws" -}}
  use-proxy-protocol: "true"
  {{ end -}}
  variables-hash-bucket-size: "128"
  server-name-hash-bucket-size: "1024"
  server-name-hash-max-size: "1024"
  server-tokens: "false"
  worker-processes: "4"
