apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-user-values
  namespace: giantswarm
data:
  values: |
    defaultPolicies:
      enabled: true
    egressMasqueradeInterfaces: eth0
    kubeProxyReplacement: strict
    k8sServiceHost: "{{ .APIInternalDomainName }}"
    k8sServicePort: "443"
    ipam:
      mode: kubernetes
    localRedirectPolicy: true
    image:
      registry: {{.DockerRegistry}}
    hubble:
      ui:
        ingress:
          enabled: true
          className: nginx
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-giantswarm"
          hosts:
          - hubble.{{ .BaseDomain }}
          tls:
          - secretName: hubble-ui-tls
            hosts:
            - hubble.{{ .BaseDomain }}
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
    app.kubernetes.io/name: cilium
  name: cilium
  namespace: giantswarm
spec:
  catalog: default
  config:
    configMap:
      name: ""
      namespace: ""
    secret:
      name: ""
      namespace: ""
  install: {}
  kubeConfig:
    context:
      name: ""
    inCluster: true
    secret:
      name: ""
      namespace: ""
  name: cilium
  namespace: kube-system
  namespaceConfig: {}
  userConfig:
    configMap:
      name: "cilium-user-values"
      namespace: "giantswarm"
    secret:
      name: ""
      namespace: ""
  version: 0.9.0
