apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-controller-app-values
  namespace: giantswarm
data:
  values: |
    controller:
      image:
        tag: "v1.11.2"
      allowSnippetAnnotations: true
      enableSSLChainCompletion: true
      resources:
        requests:
          cpu: 1
          memory: 500Mi
      autoscaling:
        targetCPUUtilizationPercentage: 80
        targetMemoryUtilizationPercentage: 80
      service:
        type: NodePort
    image:
      registry: {{ .DockerRegistry }}
    podSecurityPolicy:
      enabled: false
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  name: nginx-ingress-controller-app
  namespace: giantswarm
  labels:
    app-operator.giantswarm.io/version: 0.0.0
spec:
  catalog: giantswarm
  name: nginx-ingress-controller-app
  version: 2.30.1
  userConfig:
    configMap:
      name: nginx-ingress-controller-app-values
      namespace: giantswarm
  kubeConfig:
    inCluster: true
  namespace: kube-system
