#!/bin/bash

IPTABLES=/sbin/iptables

RULE="POSTROUTING -t nat -m addrtype ! --dst-type local ! -d {{ .PodCIDR }} -j MASQUERADE"

while : ; do
  if $IPTABLES -C ${RULE}
  then
    echo "Rule was in place"
  else
    echo "Rule not found, adding"
    $IPTABLES -A ${RULE}
  fi
  sleep 10
done
