#!/bin/sh

set -uxo pipefail

# Vault configuration
export VAULT_ADDR=https://{{ .VaultDomainName }}
export CLUSTER_NAME={{ .ClusterName }}

# Azure metadata
jwt="$(curl -s 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https://management.azure.com' -H Metadata:true | jq -r '.access_token')"
subscription_id=$(curl -s -H Metadata:true "http://169.254.169.254/metadata/instance?api-version=2017-08-01" | jq -r '.compute | .subscriptionId')
vm_name=$(curl -s -H Metadata:true "http://169.254.169.254/metadata/instance?api-version=2017-08-01" | jq -r '.compute | .name')

login_info=$(\
    docker run --rm -i\
    -v /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt\
    --net host\
    --privileged=true\
    -e VAULT_ADDR\
    -e CLUSTER_NAME\
    quay.io/giantswarm/vault:1.6.1\
    write auth/azure/login role="management-node" jwt=${jwt} subscription_id=${subscription_id} resource_group_name=${CLUSTER_NAME} vm_name=${vm_name} -format=json);

vault_token=$(echo ${login_info} | jq -r .auth.client_token)
echo "VAULT_TOKEN=${vault_token}" > /etc/tokens/node