#!/bin/bash
set -eu
# download crictl
CRICTL_VERSION=v1.13.0
wget https://github.com/kubernetes-sigs/cri-tools/releases/download/${CRICTL_VERSION}/crictl-${CRICTL_VERSION}-linux-amd64.tar.gz
tar xvf crictl-${CRICTL_VERSION}-linux-amd64.tar.gz
mv crictl /opt/bin/crictl
chmod +x /opt/bin/crictl
rm crictl-${CRICTL_VERSION}-linux-amd64.tar.gz
