#!/bin/bash
set -eu
KUBECONFIG=/etc/kubernetes/kubeconfig/addons.yaml
KUBECTL="/opt/bin/kubectl --kubeconfig=$KUBECONFIG"

while ! curl --output /dev/null --silent --head --insecure "https://{{ .APIDomainName }}"; do sleep 1 && echo 'Waiting for master'; done

# Create giantswarm, global and monitoring namespaces
NAMESPACES="giantswarm global monitoring"
for namespace in ${NAMESPACES}
do
  while true
  do
    # If namespace exists there is nothing to do so I exit the inner loop
    $KUBECTL get namespace ${namespace} && break

    # Create namespace and exit the loop if successful
    $KUBECTL create namespace ${namespace} && break

    # Something went wrong, try again
    echo "failed to create namespace ${namespace}, retrying in 5 sec"
    sleep 5s
  done
done

# label namespaces (required for network egress policies)
NAMESPACES="default giantswarm kube-system monitoring global"
for namespace in ${NAMESPACES}
do
    if ! $KUBECTL get namespaces -l name=${namespace} | grep ${namespace}; then
        while
            $KUBECTL label namespace ${namespace} name=${namespace} --overwrite=true
            [ "$?" -ne "0" ]
        do
            echo "failed to label namespace ${namespace}, retrying in 5 sec"
            sleep 5s
        done
    fi
done

# apply Security bootstrap (RBAC and PSP)
SECURITY_FILES="rbac-bindings.yaml
 psp-policies.yaml
 psp-roles.yaml
 psp-bindings.yaml"
for manifest in $SECURITY_FILES
do
    while
        $KUBECTL apply -f /srv/$manifest
        [ "$?" -ne "0" ]
    do
        echo "failed to apply /srv/$manifest, retrying in 5 sec"
        sleep 5s
    done
done

# TODO Begin Remove once all MCs will be running cilium.
# Install cilium app and wait for it to be running.
$KUBECTL apply -f /srv/apps/common/cilium-app.yaml

# Wait for cilium DS to exist and be satisfied
set +e
echo "Waiting for cilium DS to exist..."
n=0
exitcode=-1
until [ "$exitcode" -eq 0 ]
do
   $KUBECTL -n kube-system get ds cilium
   exitcode=$?
   n=$((n+1))
   if [ "$n" -ge 20 ]
   then
     echo "Failed waiting for cilium DS to exist"
     exit 1
   fi
   sleep 10
done
set -e

echo "Waiting for cilium DS to be rolled out..."
$KUBECTL -n kube-system rollout status daemonset/cilium

{{ if eq .Provider "aws" }}
# Delete legacy CNI.
$KUBECTL delete -f /srv/aws-cni.yaml --ignore-not-found=true || true
{{ end }}

# Delete calico
$KUBECTL delete -f /srv/calico-policy-only.yaml --ignore-not-found=true || true

# Delete kube-proxy.
for manifest in kube-proxy-sa.yaml kube-proxy-ds.yaml
do
  $KUBECTL delete -f /srv/$manifest --ignore-not-found=true || true
done

$KUBECTL delete configmap kube-proxy --ignore-not-found=true || true
# TODO End Remove once all MCs will be running cilium.

{{ if eq .Provider "azure" }}
# Apply CiliumLocalRedirectPolicy for cluster-autoscaler
$KUBECTL apply -f /srv/azure-ad-pod-identity-lrp.yaml
{{ end }}

# apply k8s addons
MANIFESTS="default-storage-class.yaml
 vault-token-reviewer.yaml"

for manifest in $MANIFESTS
do
    while
        $KUBECTL apply --force -f /srv/$manifest
        [ "$?" -ne "0" ]
    do
        echo "failed to apply /srv/$manifest, retrying in 5 sec"
        sleep 5s
    done
done

# Wait for App CRD to exist.
while ! $KUBECTL get crd apps.application.giantswarm.io ; do sleep 1 && echo 'Waiting for App CRD to exist'; done

# Apply all apps.
$KUBECTL apply -f /srv/apps/ --recursive

echo "Addons successfully installed"
