#!/bin/bash
{{if eq .Provider "azure" }}
# On Azure wait for waagent.service to finish provisioning.
WAA_FILE="/var/lib/waagent/provisioned"
until test -f ${WAA_FILE}; do
    echo "Waiting for waagent.service to finish provisioning."
    sleep 5
done
sleep 30s
{{end}}
{{ if eq .NodeType "master" }}
domains="{{ .ETCDDomainName }} {{ .APIDomainName }} {{ .VaultDomainName }}"
{{ else }}
domains="{{ .APIDomainName }} {{ .VaultDomainName }}"
{{ end }}
for domain in $domains; do
  until nslookup $domain; do
      echo "Waiting for domain $domain to be available"
      sleep 5
  done
  echo "Successfully resolved domain $domain"
done
