apiVersion: v1
kind: ConfigMap
metadata:
  name: azuredisk-csi-driver-user-values
  namespace: giantswarm
data:
  values: |
    image:
      baseRepo: {{ .DockerRegistry }}/giantswarm/
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  name: azuredisk-csi-driver
  namespace: giantswarm
spec:
  catalog: control-plane-catalog
  config:
    configMap:
      name: ""
      namespace: ""
    secret:
      name: ""
      namespace: ""
  install: {}
  kubeConfig:
    context:
      name: ""
    inCluster: true
    secret:
      name: ""
      namespace: ""
  name: azuredisk-csi-driver-app
  namespace: kube-system
  namespaceConfig: {}
  userConfig:
    configMap:
      name: "azuredisk-csi-driver-user-values"
      namespace: "giantswarm"
    secret:
      name: ""
      namespace: ""
  version: v1.21.0-gs1

