apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  name: azure-cloud-node-manager
  namespace: giantswarm
spec:
  catalog: control-plane-test-catalog
  config:
    configMap:
      name: ""
      namespace: ""
    secret:
      name: ""
      namespace: ""
  install: {}
  kubeConfig:
    context:
      name: ""
    inCluster: true
    secret:
      name: ""
      namespace: ""
  name: azure-cloud-node-manager-app
  namespace: kube-system
  namespaceConfig: {}
  userConfig:
    configMap:
      name: ""
      namespace: ""
    secret:
      name: ""
      namespace: ""
  version: v1.1.17-gs1-d1e4ab3b92d8e6e358d1dd567efa046d1ed55be2

