apiVersion: v1
kind: ConfigMap
metadata:
  name: azure-scheduled-events-user-values
  namespace: giantswarm
data:
  values: |
    Installation:
      V1:
        Registry:
          Domain: {{ .DockerRegistry }}
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  name: azure-scheduled-events
  namespace: giantswarm
spec:
  catalog: default
  config:
    configMap:
      name: "" 
      namespace: ""
    secret:
      name: ""
      namespace: ""
  install: {}
  kubeConfig:
    context:
      name: ""
    inCluster: true
    secret:
      name: ""
      namespace: ""
  name: azure-scheduled-events-app
  namespace: kube-system
  namespaceConfig: {}
  userConfig:
    configMap:
      name: "azure-scheduled-events-user-values"
      namespace: "giantswarm"
    secret:
      name: ""
      namespace: ""
  version: 0.8.0

