apiVersion: v1
kind: ConfigMap
metadata:
  name: azure-cloud-node-manager-user-values
  namespace: giantswarm
data:
  values: |
    image:
      registry: {{ .DockerRegistry }}
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  name: azure-cloud-node-manager
  namespace: giantswarm
  labels:
    app-operator.giantswarm.io/version: 0.0.0
spec:
  catalog: control-plane-catalog
  config:
    configMap:
      name: ""
      namespace: ""
    secret:
      name: ""
      namespace: ""
  install: {}
  kubeConfig:
    context:
      name: ""
    inCluster: true
    secret:
      name: ""
      namespace: ""
  name: azure-cloud-node-manager-app
  namespace: kube-system
  namespaceConfig: {}
  userConfig:
    configMap:
      name: "azure-cloud-node-manager-user-values"
      namespace: "giantswarm"
    secret:
      name: ""
      namespace: ""
  version: v1.24.6-gs1

